allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: false
  vue-demi: false

shellEmulator: true

trustPolicy: always
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver
