services:
  app:
    # image: "mcr.microsoft.com/devcontainers/base:noble"
    build:
      context: .
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      # Mounts your local project folder to /workspace in the container
      - ../..:/workspaces:cached
    command: sleep infinity
